services:
  dashboard:
    container_name: content-sentinel
    image: content-sentinel:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    restart: unless-stopped