name: Gitleaks

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install and run Gitleaks
        run: |
          wget https://github.com/zricethezav/gitleaks/releases/download/v8.23.3/gitleaks_8.23.3_linux_x64.tar.gz
          tar -xzf gitleaks_8.23.3_linux_x64.tar.gz
          ./gitleaks detect --source . -v --config .gitleaks.toml
          
  trigger-release:
    needs: gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Release Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          event-type: gitleaks-success
